### ISSUE TITLE
our web site is stale

### ISSUE THREAD

**Issue by chadmiller** [cforlando/meta#15]
Last updated in 2015. It looks like we aren't technical at all.

We could use Github pages with DNS CNAME, and host nothing ourselves. We could host something somewhere. 

* https://github.com/cforlando/cforlando.github.io
** https://cforlando.github.io/
** https://help.github.com/articles/quick-start-setting-up-a-custom-domain/
* https://github.com/brigadehub/brigadehub#production-install
** Need Node expert to volunteer to admin and maintain.
** Need Theme.
** Need hosting and secret credentials.

**Comment by devdupont** [comment]
I am going to get a version of brigadehub functional by the next meeting. It won't be custom to us yet, but it will be ready for tinkering.

**Comment by devdupont** [comment]
Testing brigade hub

**Comment by Erin-Denton** [comment]
Brigade Hub Live! Still some bugs but I can close this.
